# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    tags:
      - "v*.*.*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2022

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      # Runs a set of commands using the runners shell
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Restore Packages
        run: nuget restore Saga.sln

      - name: Build solution
        run: msbuild Saga.sln -t:rebuild -property:Configuration=Release

      - name: Zip build
        run: Compress-Archive -Path "D:/a/Saga/Saga/bin/Release/*" -Destination Saga.zip

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: saga.zip
